### ISSUE TITLE
希望新增dark+的向上向下置頂

### ISSUE THREAD

**Issue by chenshinshi** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#12]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-block/assets/125173405/56324e1d-0330-4176-9e6f-80912d2a3d6b)
對這種情況非常有幫助：做視頻筆記時視頻塊始終置頂，筆記過長時視頻塊也能顯示。https://ld246.com/article/1693477519814

**Comment by Zuoqiu-Yingyi** [comment]
@chenshinshi 我找到了一种更好的实现方式, 你看看这种可以嘛
![思源笔记-功能示范-37](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-block/assets/49649786/b72977af-3bdf-4bd2-b64d-dc800eb08566)

**Comment by chenshinshi** [comment]
好好好！
