### ISSUE TITLE
【bug】导出样式启用禁用菜单项不存在

### ISSUE THREAD

**Issue by hackerhui** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#22]
版本2.11.4版本思源
块菜单>插件>自定义样式
导出样式，启用/禁用，不存在

**Comment by Zuoqiu-Yingyi** [comment]
> 块菜单>插件>自定义样式 导出样式，启用/禁用，不存在

仅支持在文档一级禁用导出样式, 也就是说该菜单项仅存在于文档块块菜单中
