### ISSUE TITLE
无法保存目录插件的状态

### ISSUE THREAD

**Issue by yunyan0228** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#24]
和目录插件有冲突，用目录插件生成的目录块，在改变块属性后，下次登录会恢复原来的块状态

**Comment by Zuoqiu-Yingyi** [comment]
经过我的测试, 这是因为 `目录插件` 在文档加载时会使用 API `/api/block/updateBlock` 更新所插入的目录块, 这会导致块属性丢失, 我先去确认一下这是思源 API 的 bug 还是目录插件的兼容性问题

**Comment by Zuoqiu-Yingyi** [comment]
确定了, 使用 API /api/block/updateBlock 更新的块若未使用 IAL Token 设置块属性, 那么块属性会被重置, 是该 API 的特性

那么可能需要向目录插件作者反馈该问题了
