### ISSUE TITLE
列表块使用 列表-导图视图 功能后，针对子项较多，内容较长的列表块，难以选中菜单按钮

### ISSUE THREAD

**Issue by dxtk07** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#3]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-block/assets/43538499/b91200b9-4dc6-4bd8-8fda-30ccb95bdd33)
红圈处鼠标移过去就没了

**Comment by Zuoqiu-Yingyi** [comment]
使用快捷键 <kbd>Shift + ↑</kbd> 选择指定的块, 然后使用快捷键 <kbd>Ctrl + /</kbd>打开该块的块菜单

**Comment by Zuoqiu-Yingyi** [comment]
REF: https://github.com/Zuoqiu-Yingyi/siyuan-plugin-custom-block/commit/346e78e1a30cffe6604ef02c92e2eddf8d61dc0e
