### ISSUE TITLE
【bug】新版本思源自定义块插件的列表导图视图模式出现位置出现错乱

### ISSUE THREAD

**Issue by congSjwbsz** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#31]
![image](https://github.com/user-attachments/assets/92fca7bd-485f-4aa7-9e1d-e88c964dd3a8)
![image](https://github.com/user-attachments/assets/13b4f279-12cf-4ae2-9c27-9c3e4456ecf4)

出现问题的思源版本:3.1.12和3.1.13

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://private-user-images.githubusercontent.com/151306570/387911675-92fca7bd-485f-4aa7-9e1d-e88c964dd3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDgxMzgsIm5iZiI6MTczMjEwNzgzOCwicGF0aCI6Ii8xNTEzMDY1NzAvMzg3OTExNjc1LTkyZmNhN2JkLTQ4NWYtNGFhNy05ZTFkLWU4OGM5NjRkZDNhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMzAzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDEwNzEyZjA2NWQ5MjViOWZhMTNiY2Y2NmY5MWE3NDFiMTM5ZGRlZjNmYzg4YzRlYjljNDQwNGEzNjJmZmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KrJagDZj7saPDXz5X1aEG_rauiBBFn7lQCdqPSXKzCk)

我在 `v3.1.13` 未复现该问题👀

![image](https://github.com/user-attachments/assets/c745b3cc-6e87-4a2d-b37c-f505655638f6)
