### ISSUE TITLE
增加一个表格与页面等宽的功能

### ISSUE THREAD

**Issue by Clymer-git** [Zuoqiu-Yingyi/siyuan-plugin-custom-block#34]
希望能增加一个表格功能，将表格自适应为页面等宽。（有一些主题是带有“视图选择”菜单，可以将表格调整为“页面宽度”，但是遇到一些更加喜欢的主题却不带“视图选择”，只能遗憾放弃）

**Comment by Zuoqiu-Yingyi** [comment]
全宽显示 `width: full` 已支持表格块
